api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]

#    # ugh, because of grid-bundle.  Maybe 2 bundles, grid-bundle and api-grid-bundle?
#    defaults:
#        pagination_enabled: true
#        pagination_client_enabled: false
#        # To allow partial pagination for all resource collections.
#        # This improves performances by skipping the `COUNT` query.
#        pagination_partial: false
#        pagination_items_per_page: 40
#        pagination_client_items_per_page: true
